---
- name: playbook test
  hosts: test
  become: true

  tasks:
          - name: copy /etc/shadow
            copy:
                    src: /etc/shadow
                    dest: /tmp/shadow.copy
                    mode: 0000
                    remote_src: true #use only if the playbook fails with become
