#test playbook to gather ansible facts on the remote host and write to a file on the remote host
#
---
- name: gather ansible facts
  hosts: test
  become: true

  tasks:
          - name: Print all available facts
            ansible.builtin.debug:
                    var: ansible_facts
            register: server_output
          - name: collect output
            ansible.builtin.copy:
                    content: "{{server_output}}"
                    dest: /tmp/out.log
            delegate_to: localhost
