---
- hosts: LINUX
  tasks:
      - name: Check for Process
        shell: if ps -eaf | egrep 'apache|http'|grep -v grep > /dev/null ;then echo ‘process_running’;else echo ‘process_not_running’;fi
        ignore_errors: true
        register: app_process_check
