---
- hosts: SOLARIS
  become: true
  become_user: root
  tasks:
     - replace:
         path: /export/home/ansible/test
         regexp: 'this is a test'
         replace: 'this is not a test'
         backup: yes
