---
- hosts: SOLARIS
  become: true
  become_user: root
  tasks:
# task to backup sshd_config and replace prl from yes to no if required
    - replace:
        path: /etc/ssh/sshd_config
        regexp: 'PermitRootLogin yes'
        replace: 'PermitRootLogin no'
        backup: yes
# task to restart SSHD
    - name: Start SSHD service
      service:
        name: ssh
        state: restarted
